package task

import (
	"context"
)

// Reporter is a callback used to send results back to the cluster.
type Reporter func(id string, val any, err error)

// TaskInterface defines the behavior of a task that can be managed by the cluster.
type TaskInterface interface {
	// ID returns the task's unique identifier.
	ID() string

	// SetID Updates the task ID manually.
	// Do not call SetID after the task has been added to a cluster.
	// Doing so will break the internal mapping and the task may become unmanageable.
	SetID(id string)

	// Fn returns the underlying function to be executed.
	Fn() TaskFunc

	// Clone creates a deep copy of the task.
	// The cluster calls this automatically during AddTask to ensure
	// that each execution has its own independent state and to
	// prevent side effects from external modifications.
	Clone() TaskInterface
}

// TaskFunc defines the signature of the function containing the job logic.
// If you leave the id empty, a unique ID will be automatically generated by the cluster during the Submit() call.
type TaskFunc func(
	id string,
	workerCtx context.Context,
	cancelled <-chan struct{},
	report Reporter,
)

type task struct {
	id string
	fn TaskFunc
}

// NewTask creates and returns a new task instance with a given ID and function.
func NewTask(id string, fn TaskFunc) TaskInterface {
	return &task{
		id: id,
		fn: fn,
	}
}

func (t *task) ID() string {
	return t.id
}

func (t *task) SetID(id string) {
	t.id = id
}

func (t *task) Fn() TaskFunc {
	return t.fn
}

func (t *task) Clone() TaskInterface {
	return &task{
		id: t.id,
		fn: t.fn,
	}
}
